version: '2.4'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: restaurants

  restaurants-api:
    build: .
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"